// Preserve the existing vanilla-recipe classification when reading the wiki's
// replacement crafting table, which no longer contains Lua section markers.
export const VANILLA_CRAFTING_NAMES = new Set<string>([
  "Acacia Door",
  "Acacia Fence",
  "Acacia Fence Gate",
  "Acacia Slab",
  "Acacia Stairs",
  "Activator Rail",
  "Andesite",
  "Anvil",
  "Birch Door",
  "Birch Fence",
  "Birch Fence Gate",
  "Birch Planks",
  "Birch Slab",
  "Birch Stairs",
  "Black Carpet",
  "Black Hardened Clay",
  "Black Stained Glass",
  "Black Stained Glass Pane",
  "Black Wool",
  "Blaze Powder",
  "Block of Coal",
  "Block of Diamond",
  "Block of Emerald",
  "Block of Gold",
  "Block of Iron",
  "Block of Lapis Lazuli",
  "Block of Quartz",
  "Block of Redstone",
  "Blue Carpet",
  "Blue Hardened Clay",
  "Blue Stained Glass",
  "Blue Stained Glass Pane",
  "Blue Wool",
  "Boat",
  "Bone Meal",
  "Book",
  "Bookshelf",
  "Bowl",
  "Bread",
  "Brewing Stand",
  "Brick Slab",
  "Brick Stairs",
  "Bricks",
  "Brown Carpet",
  "Brown Hardened Clay",
  "Brown Stained Glass",
  "Brown Stained Glass Pane",
  "Brown Wool",
  "Bucket",
  "Cake",
  "Carpet",
  "Carrot on a Stick",
  "Cauldron (item)",
  "Chest",
  "Chiseled Quartz Block",
  "Chiseled Sandstone",
  "Chiseled Stone Bricks",
  "Clay",
  "Clock",
  "Coarse Dirt",
  "Cobblestone Slab",
  "Cobblestone Stairs",
  "Cobblestone Wall",
  "Comparator",
  "Compass",
  "Cookie",
  "Crafting Table",
  "Cyan Carpet",
  "Cyan Dye",
  "Cyan Hardened Clay",
  "Cyan Stained Glass",
  "Cyan Stained Glass Pane",
  "Cyan Wool",
  "Dark Oak Door",
  "Dark Oak Fence",
  "Dark Oak Fence Gate",
  "Dark Oak Planks",
  "Dark Oak Slab",
  "Dark Oak Stairs",
  "Dark Prismarine",
  "Daylight Detector",
  "Detector Rail",
  "Diamond Axe",
  "Diamond Hoe",
  "Diamond Pickaxe",
  "Diamond Shovel",
  "Diamond Sword",
  "Diorite",
  "Dispenser",
  "Dropper",
  "Enchantment Table",
  "Ender Chest",
  "Eye of Ender",
  "Firework Rocket",
  "Firework Star",
  "Fishing Rod",
  "Flint and Steel",
  "Flower Pot",
  "Furnace",
  "Glass Bottle",
  "Glass Pane",
  "Glistering Melon Slice",
  "Glowstone",
  "Gold Ingot",
  "Gold Nugget",
  "Golden Apple",
  "Golden Axe",
  "Golden Carrot",
  "Golden Hoe",
  "Golden Pickaxe",
  "Golden Shovel",
  "Golden Sword",
  "Granite",
  "Gray Carpet",
  "Gray Hardened Clay",
  "Gray Stained Glass",
  "Gray Stained Glass Pane",
  "Gray Wool",
  "Green Carpet",
  "Green Hardened Clay",
  "Green Stained Glass",
  "Green Stained Glass Pane",
  "Green Wool",
  "Hay Bale",
  "Hopper",
  "Iron Axe",
  "Iron Bars",
  "Iron Boots",
  "Iron Chestplate",
  "Iron Door",
  "Iron Helmet",
  "Iron Hoe",
  "Iron Ingot",
  "Iron Leggings",
  "Iron Pickaxe",
  "Iron Shovel",
  "Iron Sword",
  "Iron Trapdoor",
  "Item Frame",
  "Jack o' Lantern",
  "Jacob's Participation Medal",
  "Jalapeno Book",
  "Jasper Power Scroll",
  "Jerry Helmet",
  "Jinxed Voodoo Doll",
  "Juicy Healing Melon",
  "Juicy Nozzle",
  "Juju Shortbow",
  "Jukebox",
  "Jumbo Backpack",
  "Jungle Biome Stick",
  "Jungle Door",
  "Jungle Fence",
  "Jungle Fence Gate",
  "Jungle Planks",
  "Jungle Slab",
  "Jungle Stairs",
  "Ladder",
  "Lead",
  "Leather",
  "Lever",
  "Light Blue Carpet",
  "Light Blue Dye",
  "Light Blue Hardened Clay",
  "Light Blue Stained Glass",
  "Light Blue Stained Glass Pane",
  "Light Blue Wool",
  "Light Gray Carpet",
  "Light Gray Hardened Clay",
  "Light Gray Stained Glass",
  "Light Gray Stained Glass Pane",
  "Light Gray Wool",
  "Light Weighted Pressure Plate",
  "Lime Carpet",
  "Lime Hardened Clay",
  "Lime Stained Glass",
  "Lime Stained Glass Pane",
  "Lime Wool",
  "Magenta Carpet",
  "Magenta Dye",
  "Magenta Hardened Clay",
  "Magenta Stained Glass",
  "Magenta Stained Glass Pane",
  "Magenta Wool",
  "Magma Cream",
  "Map",
  "Melon",
  "Melon Seeds",
  "Minecart",
  "Minecart with Furnace",
  "Minecart with Hopper",
  "Minecart with TNT",
  "Moss Stone",
  "Mossy Cobblestone Wall",
  "Mossy Stone Bricks",
  "Mushroom Stew",
  "Nether Brick Fence",
  "Nether Brick Slab",
  "Nether Brick Stairs",
  "Nether Bricks",
  "Noteblock",
  "Oak Door",
  "Oak Fence",
  "Oak Fence Gate",
  "Oak Slab",
  "Oak Stairs",
  "Orange Carpet",
  "Orange Hardened Clay",
  "Orange Stained Glass",
  "Orange Stained Glass Pane",
  "Orange Wool",
  "Packed Ice",
  "Paper",
  "Pillar Quartz Block",
  "Pink Carpet",
  "Pink Hardened Clay",
  "Pink Stained Glass",
  "Pink Stained Glass Pane",
  "Pink Wool",
  "Piston",
  "Planks",
  "Polished Andesite",
  "Polished Diorite",
  "Polished Granite",
  "Powered Rail",
  "Prismarine",
  "Prismarine Bricks",
  "Pumpkin Pie",
  "Pumpkin Seeds",
  "Purple Carpet",
  "Purple Dye",
  "Purple Hardened Clay",
  "Purple Stained Glass",
  "Purple Stained Glass Pane",
  "Purple Wool",
  "Quartz Slab",
  "Quartz Stairs",
  "Rabbit Stew",
  "Rail",
  "Red Carpet",
  "Red Chiseled Sandstone",
  "Red Hardened Clay",
  "Red Sandstone",
  "Red Sandstone Slab",
  "Red Sandstone Stairs",
  "Red Stained Glass",
  "Red Stained Glass Pane",
  "Red Wool",
  "Redstone Torch",
  "Repeater",
  "Sandstone",
  "Sandstone Slab",
  "Sandstone Stairs",
  "Sea Lantern",
  "Shears",
  "Sign",
  "Slime Block",
  "Snow Block",
  "Snow Layer",
  "Spruce Door",
  "Spruce Fence",
  "Spruce Fence Gate",
  "Spruce Planks",
  "Spruce Slab",
  "Spruce Stairs",
  "Stick",
  "Sticky Piston",
  "Stone Axe",
  "Stone Brick Slab",
  "Stone Brick Stairs",
  "Stone Bricks",
  "Stone Button",
  "Stone Hoe",
  "Stone Pickaxe",
  "Stone Pressure Plate",
  "Stone Shovel",
  "Stone Slab",
  "Stone Sword",
  "Sugar",
  "TNT",
  "Torch",
  "Trapped Chest",
  "Tripwire Hook",
  "Wheat",
  "White Carpet",
  "White Hardened Clay",
  "White Stained Glass",
  "White Stained Glass Pane",
  "White Wool",
  "Wooden Axe",
  "Wooden Button",
  "Wooden Hoe",
  "Wooden Pickaxe",
  "Wooden Pressure Plate",
  "Wooden Shovel",
  "Wooden Sword",
  "Wooden Trapdoor",
  "Yellow Carpet",
  "Yellow Hardened Clay",
  "Yellow Stained Glass",
  "Yellow Stained Glass Pane",
  "Yellow Wool"
]);
